spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    show-sql: false

app:
  auth:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}

logging:
  level:
    "[de.dermatrack]": INFO
    "[org.hibernate.SQL]": WARN
