spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    show-sql: true

logging:
  level:
    "[de.dermatrack]": DEBUG
    "[org.hibernate.SQL]": DEBUG

app:
  auth:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}
